name: Updates after PR merge
on:
  push:
    branches: [ main ]

jobs:
  Migrations:
    name: Run DB Migrations
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Setup - Checkout code
      uses: actions/checkout@v1

    - name: Create docker image
      run: docker build -t ci .
    
    - name: Push migrations
      run: docker run --rm -e DATABASE_URL=${{ secrets.DATABASE_URL }} ci npx prisma migrate deploy

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: josiahsayers15/home-automation-helper:latest
