name: Updates after PR merge
on:
  push:
    branches: [ main ]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  Migrations:
    name: Run DB Migrations
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Setup - Checkout code
      uses: actions/checkout@v1

    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Instal dependencies
      run: npm ci

    - name: Push migrations
      run: npx prisma migrate deploy

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup - Checkout code
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            josiahsayers15/home-automation-helper
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
